### ISSUE TITLE
本地测试运行重启后页面一直空白，提示 ： WARN No layout: index.html

### ISSUE THREAD

**Issue by puppetdevz** [xaoxuu/hexo-theme-resume#22]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-resume/releases/latest) version of Resume.
- [x] I have reviewed [guidelines for resume](https://resume.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Describe your question 

我从 https://github.com/xaoxuu/resume-docs 下载了master分支的代码，想要参考 https://resume.js.org/zh-cn/ 进行修改。下载后执行了以下命令：
~~~shell
npm install
npm run start
~~~
访问 http://localhost:4000 ，此时页面全是白的，没有信息。终端报 WARN No layout: index.html

![image](https://user-images.githubusercontent.com/46890209/158780699-f904335e-2bc1-4dc1-a3f2-9f0ea3f71400.png)

我参考了 #7  但是没有作用。

### Node.js and NPM Information

```
v14.17.6
6.14.15
```

### Package dependencies Information

```
hexo-site@ /Users/puppet/VSCodeProjects/puppet-resume
├── UNMET PEER DEPENDENCY hexo@5.4.1
├── hexo-autonofollow@1.0.1
├── hexo-deployer-git@3.0.0 (github:hexojs/hexo-deployer-git#7d93124646bf34b52d4b38725fe1163f3765fc9f)
├── hexo-lazyload-image@1.0.10
├── hexo-neat@1.0.9
├── hexo-offline@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@3.3.0
├── hexo-renderer-stylus@2.0.1
└── hexo-server@2.0.0
```

### Hexo Configuration

```yml
# Hexo Configuration

# Site
language: zh-CN

shortcut_icon: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/avatar/avatar.png
favicon: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/avatar/avatar.png
avatar: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/avatar/avatar.png

# 主题
theme: resume
theme_config:
  robots: index,follow
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://resume.js.org
# url: http://localhost:4000
root: /
permalink: posts/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code

# Directory
source_dir: src
public_dir: public
skip_render: README.md
exclude: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
max_open_file: 100
multi_thread: true
filename_case: 0
render_drafts: false
post_asset_folder: false
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: '    '

index_generator:
  path: 'index'
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 0
category: 0
tag: 0

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
logger: false
logger_format:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: 'YYYY-MM-DD dddd'
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname:

# Extensions
## Plugins: https://github.com/tommy351/hexo/wiki/Plugins
## Themes: https://github.com/tommy351/hexo/wiki/Themes

exclude_generator:

# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true


import:
  meta:
  - "<meta name='theme-color' content='#FFFFFF'>"
  - "<meta name='msapplication-TileColor' content='#1BC3FB'>"
  - "<meta name='msapplication-config' content='https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/favicon/browserconfig.xml'>"
  link:
  - "<link rel='shortcut icon' type='image/x-icon' href='https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/favicon/favicon.ico'>"
  - "<link rel='icon' type='image/x-icon' sizes='32x32' href='https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/favicon/favicon-32x32.png'>"
  - "<link rel='apple-touch-icon' type='image/png' sizes='180x180' href='https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/favicon/apple-touch-icon.png'>"
  - "<link rel='mask-icon' color='#1BC3FB' href='https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/favicon/safari-pinned-tab.svg'>"
  - "<link rel='manifest' href='https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/favicon/site.webmanifest'>"
  # script:

# Offline
## Config passed to sw-precache
## https://github.com/JLHwung/hexo-offline
# offline config passed to sw-precache.
offline:
  maximumFileSizeToCacheInBytes: 10485760
  staticFileGlobs:
    - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: true
  runtimeCaching:
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdn.jsdelivr.net
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdnjs.cloudflare.com

nofollow:
  enable: true
  exclude:
    - xaoxuu.com


# npm i hexo-neat
neat_enable: true



# 图片懒加载
lazyload:
  enable: true
  onlypost: false
  loadingImg: https://img.vim-cn.com/92/d570170f4f12e1ee829ca0e85a7dffeb77343a.svg


# 百度统计key
# baidu_analytics_key: cd037d28d6a6eaf5b81b7c9b024741cc

# Deployment
## Docs: http://zespia.tw/hexo/docs/deployment.html
deploy:
  - type: git
    repo: https://github.com/xaoxuu/resume.js.org.git
    branch: master
    message: update pages

feed:
  type: atom
  path: atom.xml
  limit: 20

```

### Resume Configuration

```yml
完全没有修改过，下载后想先尝试运行
```

## Other Information 
使用的是Edge浏览器
![image](https://user-images.githubusercontent.com/46890209/158781212-bb91aab8-e8d0-4937-b719-00aceb86ba25.png)
