### ISSUE TITLE
懒加载无法使用自定义图片

### ISSUE THREAD

**Issue by JohnnyLin12** [xaoxuu/hexo-theme-resume#8]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/xaoxuu/hexo-theme-resume/releases/latest) version of Resume.
- [ ] I have reviewed [guidelines for resume](https://resume.js.org), which does not help me.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### Resume Configuration

```yml

```

## Other Information 

在 网站配置文件下增加
lazyload:
  enable: true 
  onlypost: true  # 是否只对文章的图片做懒加载
  loadingImg: \img\mypic\loading.gif

使用我放在img目录下mypic目录下的loading.gif图片作为懒加载时的加载图片，没有生效，还是使用的默认图片。
再使用谷歌浏览器f12查看，也没有显示加载图片找不到资源的超时提示。
不知道是不是路径写错了，请作者指点一下。感谢！！

**Comment by xaoxuu** [comment]
改成这样：
```yaml
lazyload:
  enable: true
  onlypost: false
  loadingImg: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/placeholder/c617bfd2497fcea598e621413e315c368f8d8e.svg
```
